### ISSUE TITLE
RustyBGP performance issues

### ISSUE THREAD

**Issue by jopietsch** [osrg/rustybgp#114]
Working on my next blog post about testing performance of bgp software. Here is a draft:  https://github.com/elegantnetwork/elegantnetwork.github.io/blob/master/_drafts/2021-08-120-comparing-open-source-bgp-internet-routes.md, I found a bunch of issues with rustybgp. I cannot replicate the performance that you have shown. Also, there are other issues that I've written up in the draft blog post

**Comment by fujita** [comment]
Can you give an example command to test RustyBGP with your bgperf with a mrt file?

**Comment by jopietsch** [comment]
python3 bgperf.py bench -trustybgp -n30 -s -p800000 -mbgpdump2 --mrt-file=<full path to mrt file>

that creates 30 bgpdump2 neighbors. It probably depends on the hardware that you use. 

you will have to create all the containers beforehand.
'''bgperf update rustybgp
bgperf update gobgp 
bgperf update bgpdump2'''

**Comment by fujita** [comment]
With some fixes and improvement, rustybgp gives the better performance than bird. Can you try the latest rustybgp (4640eb4) on your env? On my env (ec2 c5a.12xlarge), I got the following results: 

`bgperf.py bench -trustybgp -n30 -s -p800000 -mbgpdump2 --mrt-file=/home/ubuntu/git/bgperf/rib.20210801.0000`

- rustybgp

``
Max cpu: 3401.23, max mem: 5.08GB
Min %idle 8.04, Min mem free 70.49GB
Time since first received prefix: 51
total time: 82.05s
``
- bird

``
bird: v2.0.8-59-gf761be6b
Max cpu: 101.46, max mem: 2.79GB
Min %idle 85.48, Min mem free 73.71GB
Time since first received prefix: 148
total time: 175.37s
``

**Comment by jopietsch** [comment]
thanks for this work, it's fantstic!
